name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.4"  # Specify the Python version

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install project dependencies

    # 4. Run tests
    - name: Run tests
      run: |
        pytest --disable-warnings  # Run your tests with Pytest

    # Optional: Report test coverage
    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./htmlcov  # Adjust to your coverage report location
